[HER-49]Create detections query
NerdsComputing/hermes.api pull request #24
Opened 2021-07-08 17:01 UTC by Urzica-Platon-Casian

## Description
Create query with mocked data

## Related
[HER-49](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-49)

2021-07-08 18:41 UTC, RaduBuciuceanu requested changes
Not for now! But I need more power. I'll try to get it till tomorrow.

2021-07-09 07:17 UTC, RaduBuciuceanu commented on src/Presentation/GraphQL/Base/TDetection.cs
> +}
Should we move this graph type under the `Detections/Types` feature folder?

2021-07-09 07:17 UTC, RaduBuciuceanu commented on src/Presentation/GraphQL/Base/Schema.cs
> +            Query = new DetectionQuery();
Should we maintain the old Query? Should we register the new one as it's child?

2021-07-09 07:17 UTC, RaduBuciuceanu commented on src/Presentation/GraphQL/Base/DetectionQuery.cs
> +}
Should we move this folder under the `Detections/Query` file?

2021-07-09 07:18 UTC, RaduBuciuceanu requested changes
Here is the power. :smile:

2021-07-09 07:19 UTC, miutamihai requested changes
![image](https://user-images.githubusercontent.com/23569938/125039394-1a43b980-e09f-11eb-9ce1-4a5ff2f27329.png)
Das is no bueno, amigito. Let's remake our commit history so that we remove that ugly `temp` :smile:

2021-07-09 12:44 UTC, RaduBuciuceanu approved these changes

2021-07-09 12:44 UTC, miutamihai approved these changes

2021-07-09 12:44 UTC, merged

2021-07-09 12:44 UTC, TBiannca approved these changes