[HER-80]Create MCamera business model
NerdsComputing/hermes.api pull request #41
Opened 2021-07-23 09:39 UTC by Urzica-Platon-Casian

## Description
-     it will live inside business layer
-     it will be used as a return type for our business command
-     it will contain:
        - id
        - longitude
        - latitude

## Related
[HER-80](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?issueParent=10022&selectedIssue=HER-80)

2021-07-23 09:46 UTC, andreea-dumitrascu submitted a review, later dismissed

2021-07-26 06:25 UTC, RaduBuciuceanu submitted a review, later dismissed

2021-07-26 07:01 UTC, danidoff submitted a review, later dismissed

2021-07-26 07:15 UTC, RaduBuciuceanu requested changes

2021-07-26 07:15 UTC, RaduBuciuceanu commented on src/Business/Camera/Common/Models/MCamera.cs
> +        public int Id { get; set; }
Shouldn't it be a string here?

2021-07-26 07:18 UTC, Urzica-Platon-Casian commented on src/Business/Camera/Common/Models/MCamera.cs
> +        public int Id { get; set; }
Done

2021-07-26 07:27 UTC, andreea-dumitrascu approved these changes

2021-07-26 07:30 UTC, RaduBuciuceanu approved these changes

2021-07-26 07:30 UTC, merged