Her 32
NerdsComputing/hermes.api pull request #6
Opened 2021-06-24 17:16 UTC by ConstantinescuAndrei

Configure multiple environments

[HER-32](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-32)

2021-06-24 18:15 UTC, RaduBuciuceanu requested changes
@Urzica-Platon-Casian , @andreea-dumitrascu , @TBiannca Waiting for your reviews, before :wink:

2021-06-24 18:15 UTC, RaduBuciuceanu commented on src/Presentation/Properties/launchSettings.json
> +      }
That's not so easy :smile: 
@danidoff :point_up:

2021-06-25 07:28 UTC, andreea-dumitrascu commented on src/Presentation/Startup.cs
> +            else
Should you have used brackets here?

2021-06-25 07:31 UTC, Urzica-Platon-Casian commented on src/Presentation/Properties/launchSettings.json
> +      }
Looks good to me.

2021-06-25 07:38 UTC, andreea-dumitrascu commented on src/Presentation/Startup.cs
> +            }
Should you have used brackets here?

2021-06-25 10:04 UTC, danidoff commented
Should we change the name of the PR like this: [HER-32]Configure multiple environments. ?

2021-06-28 06:21 UTC, RaduBuciuceanu requested changes
- Should we also remove the unused `settings.json` file?

2021-06-28 06:21 UTC, RaduBuciuceanu commented on src/Presentation/Program.cs
> +                    config.AddJsonFile("settings.default.json", optional: true, reloadOnChange: true);
Should we also configure it here to read from inside env variables also?

2021-06-28 06:28 UTC, RaduBuciuceanu requested changes

2021-06-28 06:28 UTC, RaduBuciuceanu commented on src/Presentation/settings.default.json
> +  },
Do we really need to create a `environmentVariables` section here? Won't it be enough just to have this?
```json
"environment": "Development"
```

2021-06-28 06:28 UTC, RaduBuciuceanu commented on src/Presentation/settings.default.json
> +    "DB": "server=localhost;port=3306;user=root;password=admin;database=test"
Is the name "Database" more relevant here?

2021-06-28 08:04 UTC, RaduBuciuceanu submitted a review, later dismissed
Sexy :heart_eyes:

2021-06-28 08:26 UTC, danidoff requested changes

2021-06-28 08:26 UTC, danidoff commented on src/Presentation/Program.cs
> +                    config.AddJsonFile("settings/settings.default.json", optional: true, reloadOnChange: true);
Should we rename the folder settings name with UpperCase ?

2021-06-28 08:26 UTC, danidoff commented on src/Presentation/Program.cs
> +                    config.AddJsonFile("settings/settings.default.json", optional: true, reloadOnChange: true);
Also should we remove optional and reloadOnChange?

2021-06-28 08:26 UTC, danidoff commented on src/Presentation/Startup.cs
> +            if (environmentVariable == "Development")
Should we use "Default" instead of "Development" here ?

2021-06-28 08:26 UTC, danidoff commented on src/Presentation/settings/settings.default.json
> +  "environment": "Development",
Also here, should we use "Default" instead of "Development"?

2021-06-28 08:26 UTC, danidoff commented on src/Presentation/settings/settings.default.json
> +    "ConnectionString": "server=localhost;port=3306;user=root;password=admin;database=hermes"
Should we change connection string into: "Server=127.0.0.1,3306;Database=hermes_local;User=root;Password=admin;"

2021-06-28 08:26 UTC, danidoff commented on src/Presentation/settings/settings.default.json
> +    "ConnectionString": "server=localhost;port=3306;user=root;password=admin;database=hermes"
Should we change connection string into: "Server=127.0.0.1,3306;Database=hermes;User=root;Password=admin;"

2021-06-28 09:56 UTC, RaduBuciuceanu approved these changes

2021-06-28 10:00 UTC, danidoff approved these changes

2021-06-28 10:09 UTC, merged