Her 34
NerdsComputing/hermes.api pull request #7
Opened 2021-06-24 21:58 UTC by andreea-dumitrascu

### Create Readme file
[HER-34](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-34)

2021-06-25 10:00 UTC, danidoff requested changes
Should we edit the name of the PR like this: [HER-34] Create readme file? :dancing_women:

2021-06-25 10:02 UTC, danidoff commented
Should we edit the description of the PR (add Description and Related with ##) ? :dancing_women:

2021-06-25 10:03 UTC, danidoff commented
Should we also run the deploy.dev ?

2021-06-28 06:22 UTC, RaduBuciuceanu approved these changes

2021-06-28 06:22 UTC, merged