[HER-31]Create Version endpoint
NerdsComputing/hermes.api pull request #8
Opened 2021-06-26 09:42 UTC by Urzica-Platon-Casian

## Description
Create   "/v1/api/version" endpoint

## Related
[HER-31](https://nerds-interns.atlassian.net/jira/software/projects/HER/boards/1?selectedIssue=HER-31)

2021-06-26 15:27 UTC, ConstantinescuAndrei submitted a review, later dismissed
Looks good.

2021-06-28 06:24 UTC, RaduBuciuceanu requested changes

2021-06-28 06:24 UTC, RaduBuciuceanu commented on src/Presentation/Presentation.csproj
> +    </ItemGroup>
Are we using this new referenced package? If no, should we consider removing it from references?

2021-06-28 08:03 UTC, RaduBuciuceanu approved these changes
- Should we also deploy to dev it?
- Should we also rebase with latest master?

2021-06-28 08:20 UTC, danidoff submitted a review, later dismissed

2021-06-28 09:54 UTC, RaduBuciuceanu approved these changes

2021-06-28 10:01 UTC, merged